using FitAppka.Models;
using FitAppka.Repository;
namespace FitAppka.Service.ServiceImpl
{
    public class GoalsServiceImpl : IGoalsService
    {
        private readonly IClientRepository _clientRepository;
        private readonly ICardioTrainingService _cardioService;
        private readonly IDayRepository _dayRepository;
        private readonly IDietaryTargetsService _dietaryTargetsService;

        public GoalsServiceImpl(IClientRepository clientRepository, IDietaryTargetsService dietaryTargetsService, IDayRepository dayRepository, ICardioTrainingService cardioService)
        {
            _cardioService = cardioService;
            _dayRepository = dayRepository;
            _dietaryTargetsService = dietaryTargetsService;
            _clientRepository = clientRepository;
        }

        public void UpdateGoals(CreateGoalsModel m)
        {
            SetTargetsInDaysFromToday(_clientRepository.Update(SetClientTargets(m, SetClientPreferences(m))));
        }

        private Client SetClientPreferences(CreateGoalsModel m){
            Client client = _clientRepository.GetLoggedInClient();
            client.AutoDietaryGoals = m.AutoGeneratedDietaryGoals;
            client.IncludeCaloriesBurned = m.IncludeCaloriesBurnedInBalance;
            client.TrainingTimeGoal = m.TrainingTimeGoal;
            client.KcalBurnedGoal = m.CaloriesBurnedGoal;
            return client;
        }

        private Client SetClientTargets(CreateGoalsModel m, Client client)
        {
            if (m.AutoGeneratedDietaryGoals) {
                return CountClientTargets(client);
            }
            else {
                return GetTargetsFromModel(m, client);
            }
        }


        private Client CountClientTargets(Client c)
        {
            int calorieTarget = _dietaryTargetsService.CountCalorieTarget((int) c.CaloricDemand, c.WeightChangeGoal, (double) c.PaceOfChanges);
            int proteinTarget = _dietaryTargetsService.CountProteinTarget(_dietaryTargetsService.GetLastWeightMeasurement(), calorieTarget, c.ActivityLevel);
            int fatTarget = _dietaryTargetsService.CountFatTarget(calorieTarget);
            int carbsTarget = _dietaryTargetsService.CountCarbsTarget(calorieTarget, proteinTarget, fatTarget);

            c.CalorieGoal = calorieTarget;
            c.ProteinTarget = proteinTarget;
            c.FatTarget = fatTarget;
            c.CarbsTarget = carbsTarget;
            return c;
        }

        private Client GetTargetsFromModel(CreateGoalsModel m, Client c)
        {
            c.CalorieGoal = m.CaloriesTarget;
            c.CarbsTarget = m.CarbohydratesTarget;
            c.ProteinTarget = m.ProteinsTarget;
            c.FatTarget = m.FatsTarget;
            return c;
        }

        private void SetTargetsInDaysFromToday(Client client)
        {
            foreach (var dayID in _dietaryTargetsService.GetListOfDaysIDFromToday(client))
            {
                foreach (var day in _dayRepository.GetClientDays(client.ClientId))
                {
                    if (day.DayId == dayID)
                    {
                        _dayRepository.Update(MapTargetsFromClientToDay(day, client));
                    }
                }
            }    
        }

        private Day MapTargetsFromClientToDay(Day day, Client client)
        {
            if ((bool)client.IncludeCaloriesBurned) 
            {
                int kcalBurned = _cardioService.CaloriesBurnedInDay(day.DayId);
                day.CalorieGoal = client.CalorieGoal + kcalBurned;
                day.ProteinTarget = countProteinTarget(kcalBurned, client);
                day.FatTarget = countFatTarget(kcalBurned, client);
                day.CarbsTarget = countCarbsTarget(kcalBurned, client);
            }
            else 
            {
                day.CalorieGoal = client.CalorieGoal;
                day.ProteinTarget = client.ProteinTarget;
                day.FatTarget = client.FatTarget;
                day.CarbsTarget = client.CarbsTarget;
            }

            day.KcalBurnedGoal = client.KcalBurnedGoal;
            day.TrainingTimeGoal = client.TrainingTimeGoal;
            return day;
        }


        private int countProteinTarget(int caloriesBurned, Client client)
        {
            double proteinProportion = ((double)(client.ProteinTarget * 4)) / (double)client.CalorieGoal;
            return (int)((caloriesBurned * proteinProportion) + client.ProteinTarget);

        }

        private int countFatTarget(int caloriesBurned, Client client) {
            double fatProportion = ((double)(client.FatTarget * 9)) / (double)client.CalorieGoal;
            return (int)(caloriesBurned * fatProportion + client.FatTarget);
        }

        private int countCarbsTarget(int caloriesBurned, Client client)
        {
            double carbsProportion = ((double)(client.CarbsTarget * 4)) / (double)client.CalorieGoal;
            return (int)(caloriesBurned * carbsProportion + client.CarbsTarget);
        }
    }
}
