using FitAppka.Models;
using FitAppka.Repository;
namespace FitAppka.Service.ServiceImpl
{
    public class GoalsServiceImpl : IGoalsService
    {
        private readonly IClientRepository _clientRepository;
        private readonly IDayRepository _dayRepository;
        private readonly IDietaryTargetsService _dietaryTargetsService;

        public GoalsServiceImpl(IClientRepository clientRepository, IDietaryTargetsService dietaryTargetsService, IDayRepository dayRepository)
        {
            _dayRepository = dayRepository;
            _dietaryTargetsService = dietaryTargetsService;
            _clientRepository = clientRepository;
        }

        public void UpdateGoals(CreateGoalsModel m)
        {
            SetTargetsInDaysFromToday(_clientRepository.Update(SetClientTargets(m, SetClientPreferences(m))));
        }

        private Client SetClientPreferences(CreateGoalsModel m){
            Client client = _clientRepository.GetLoggedInClient();
            client.AutoDietaryGoals = m.AutoGeneratedDietaryGoals;
            client.IncludeCaloriesBurned = m.IncludeCaloriesBurnedInBalance;
            client.TrainingTimeGoal = m.TrainingTimeGoal;
            client.KcalBurnedGoal = m.CaloriesBurnedGoal;
            return client;
        }

        private Client SetClientTargets(CreateGoalsModel m, Client client)
        {
            if (!m.AutoGeneratedDietaryGoals) {
                return GetTargetsFromModel(m, client);
            }
            else {
                return CountClientTargets(client);
            }
        }


        private Client CountClientTargets(Client c)
        {
            int calorieTarget = _dietaryTargetsService.CountCalorieTarget((int) c.CaloricDemand, c.WeightChangeGoal, (double) c.PaceOfChanges);
            int proteinTarget = _dietaryTargetsService.CountProteinTarget(_dietaryTargetsService.GetLastWeightMeasurement(), calorieTarget, c.ActivityLevel);
            int fatTarget = _dietaryTargetsService.CountFatTarget(calorieTarget);
            int carbsTarget = _dietaryTargetsService.CountCarbsTarget(calorieTarget, proteinTarget, fatTarget);

            c.CalorieGoal = calorieTarget;
            c.ProteinTarget = proteinTarget;
            c.FatTarget = fatTarget;
            c.CarbsTarget = carbsTarget;
            return c;
        }

        private Client GetTargetsFromModel(CreateGoalsModel m, Client c)
        {
            c.CalorieGoal = m.CaloriesTarget;
            c.CarbsTarget = m.CarbohydratesTarget;
            c.ProteinTarget = m.ProteinsTarget;
            c.FatTarget = m.FatsTarget;
            return c;
        }

        private void SetTargetsInDaysFromToday(Client client)
        {
            foreach (var dayID in _dietaryTargetsService.GetListOfDaysIDFromToday(client))
            {
                foreach (var day in _dayRepository.GetClientDays(client.ClientId))
                {
                    if (day.DayId == dayID)
                    {
                        day.CalorieGoal = client.CalorieGoal;
                        day.ProteinTarget = client.ProteinTarget;
                        day.FatTarget = client.FatTarget;
                        day.CarbsTarget = client.CarbsTarget;
                        day.KcalBurnedGoal = client.KcalBurnedGoal;
                        day.TrainingTimeGoal = client.TrainingTimeGoal;
                        _dayRepository.Update(day);
                    }
                }
            }    
        }


    }
}
