using FitAppka.Models;
using FitAppka.Repository;
namespace FitAppka.Service.ServiceImpl
{
    public class GoalsServiceImpl : IGoalsService
    {
        private readonly IClientRepository _clientRepository;

        public GoalsServiceImpl(IClientRepository clientRepository)
        {
            _clientRepository = clientRepository;
        }

        public void UpdateGoals(CreateGoalsModel m)
        {
            Client client = _clientRepository.GetLoggedInClient();
            client.AutoDietaryGoals = m.AutoGeneratedDietaryGoals;
            client.IncludeCaloriesBurned = m.IncludeCaloriesBurnedInBalance;
        }


    }
}
